# Generated by Django 4.2.5 on 2023-09-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='buyed_at',
            new_name='added_at',
        ),
    ]
