# Generated by Django 4.2.5 on 2023-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_buyed_at_ticket_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
